In [1]:
import pandas as pd
import numpy as np

death_03_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2003.txt", sep="\t")
death_04_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2004.txt", sep="\t")
death_05_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2005.txt", sep="\t")
death_06_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2006.txt", sep="\t")
death_07_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2007.txt", sep="\t")
death_08_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2008.txt", sep="\t")
death_09_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2009.txt", sep="\t")
death_10_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2010.txt", sep="\t")
death_11_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2011.txt", sep="\t")
death_12_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2012.txt", sep="\t")
death_13_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2013.txt", sep="\t")
death_14_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2014.txt", sep="\t")
death_15_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2015.txt", sep="\t")

In [2]:
death_04_df.head()

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,NaN,"Autauga County, AL",1001.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,373.0
1,NaN,"Baldwin County, AL",1003.0,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,18.0
2,NaN,"Baldwin County, AL",1003.0,2004.0,2004.0,All other alcohol-induced causes,A9,10.0
3,NaN,"Baldwin County, AL",1003.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,1518.0
4,NaN,"Barbour County, AL",1005.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,274.0

In [3]:
death_03_df.head()

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,NaN,"Autauga County, AL",1001.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,NaN,"Barbour County, AL",1005.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0

In [4]:
vital_stats = pd.concat([death_03_df,death_04_df,death_05_df,death_06_df,death_07_df,death_08_df,death_09_df,death_10_df,death_11_df,death_12_df,death_13_df,death_14_df,death_15_df])

In [5]:
vital_stats.sample(40)

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
3090,NaN,"Adams County, OH",39001.0,2015.0,2015.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13
3023,NaN,"Monroe County, PA",42089.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1153.0
181,NaN,"Drew County, AR",5043.0,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,173.0
4059,NaN,"Johnson County, TX",48251.0,2015.0,2015.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13
1063,NaN,"Randolph County, IL",17157.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,379.0
323,NaN,"Riverside County, CA",6065.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,178.0
3733,NaN,"Freestone County, TX",48161.0,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,188.0
1313,NaN,"Decatur County, IA",19053.0,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,100.0
1072,NaN,"Sangamon County, IL",17167.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1896.0
872,NaN,"Whitfield County, GA",13313.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,763.0
1325,NaN,"Washington County, IA",19183.0,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,249.0
3375,NaN,"Yankton County, SD",46135.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,195.0
3347,NaN,"Greene County, TN",47059.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,744.0
3128,NaN,"Montgomery County, PA",42091.0,2005.0,2005.0,Drug poisonings (overdose) Unintentional (X40-...,D1,63.0
3200,NaN,"Northampton County, PA",42095.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,22.0
457,NaN,"Prowers County, CO",8099.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,101.0
1959,NaN,"Rankin County, MS",28121.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,817.0
4079,NaN,"Tyler County, WV",54095.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,108.0
6,NaN,"Blount County, AL",1009.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,527.0
491,NaN,"Pueblo County, CO",8101.0,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0
2233,NaN,"Wheatland County, MT",30107.0,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,19.0
1211,NaN,"Pike County, IN",18125.0,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,138.0
1293,NaN,"Scott County, IA",19163.0,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,1259.0
532,NaN,"Prowers County, CO",8099.0,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,130
1082,NaN,"Scott County, IN",18143.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,195.0
1891,NaN,"Jackson County, MI",26075.0,2012.0,2012.0,All other drug-induced causes,D9,18.0
2649,NaN,"McLean County, ND",38055.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,134.0
732,NaN,"Fulton County, GA",13121.0,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,53.0
2790,NaN,"Columbus County, NC",37047.0,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,644.0
2125,NaN,"Smith County, MS",28129.0,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,156.0
131,NaN,"Maricopa County, AZ",4013.0,2007.0,2007.0,All other alcohol-induced causes,A9,351.0
649,NaN,"Seminole County, FL",12117.0,2005.0,2005.0,All other alcohol-induced causes,A9,27.0
350,NaN,"San Francisco County, CA",6075.0,2007.0,2007.0,All other alcohol-induced causes,A9,99.0
916,NaN,"Honolulu County, HI",15003.0,2012.0,2012.0,Drug poisonings (overdose) Unintentional (X40-...,D1,68.0
675,NaN,"St. Johns County, FL",12109.0,2009.0,2009.0,All other alcohol-induced causes,A9,15.0
1066,NaN,"Adams County, IN",18001.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,267.0
3709,NaN,"Fairfax County, VA",51059.0,2003.0,2003.0,Drug poisonings (overdose) Suicide (X60-X64),D2,11.0
3888,NaN,"Grayson County, VA",51077.0,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,206.0
369,NaN,"Santa Barbara County, CA",6083.0,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,2818.0
1423,NaN,"Butler County, KY",21031.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,122.0

In [6]:
# Dropping Notes and Year Code columns. Notes has too many null values and Year Code is a redundant column
vital_stats = vital_stats.drop(["Notes","Year Code"], axis = 1)
vital_stats.head()

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,"Baldwin County, AL",1003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,"Baldwin County, AL",1003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,"Baldwin County, AL",1003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,"Barbour County, AL",1005.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0

In [7]:
vital_stats.shape

(57436, 6)

In [8]:
vital_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57436 entries, 0 to 4797
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County                           57241 non-null  object
 1   County Code                      57241 non-null  float64
 2   Year                             57241 non-null  float64
 3   Drug/Alcohol Induced Cause       57241 non-null  object
 4   Drug/Alcohol Induced Cause Code  57241 non-null  object
 5   Deaths                           57241 non-null  object
dtypes: float64(2), object(4)
memory usage: 3.1+ MB

In [9]:
vital_stats.isna().sum()

County                             195
County Code                        195
Year                               195
Drug/Alcohol Induced Cause         195
Drug/Alcohol Induced Cause Code    195
Deaths                             195
dtype: int64

In [10]:
#Dropping all na values
vital_stats.dropna(inplace=True)

In [11]:
vital_stats.isna().sum()

County                             0
County Code                        0
Year                               0
Drug/Alcohol Induced Cause         0
Drug/Alcohol Induced Cause Code    0
Deaths                             0
dtype: int64

In [12]:
vital_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57241 entries, 0 to 4782
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County                           57241 non-null  object
 1   County Code                      57241 non-null  float64
 2   Year                             57241 non-null  float64
 3   Drug/Alcohol Induced Cause       57241 non-null  object
 4   Drug/Alcohol Induced Cause Code  57241 non-null  object
 5   Deaths                           57241 non-null  object
dtypes: float64(2), object(4)
memory usage: 3.1+ MB

In [21]:
vital_stats["Year"] = pd.to_datetime(vital_stats["Year"],format="%Y")

In [22]:
vital_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57241 entries, 0 to 4782
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County                           57241 non-null  object
 1   County Code                      57241 non-null  float64
 2   Year                             57241 non-null  datetime64[ns]
 3   Drug/Alcohol Induced Cause       57241 non-null  object
 4   Drug/Alcohol Induced Cause Code  57241 non-null  object
 5   Deaths                           57241 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 3.1+ MB

In [29]:
vital_stats["Drug/Alcohol Induced Cause"].value_counts()

All other non-drug and non-alcohol causes             40337
Drug poisonings (overdose) Unintentional (X40-X44)     7573
All other alcohol-induced causes                       6123
Drug poisonings (overdose) Suicide (X60-X64)           1465
Drug poisonings (overdose) Undetermined (Y10-Y14)       761
All other drug-induced causes                           628
Alcohol poisonings (overdose) (X45, X65, Y15)           349
Drug poisonings (overdose) Homicide (X85)                 5
Name: Drug/Alcohol Induced Cause, dtype: int64

In [32]:
cod = ["Drug poisonings (overdose) Unintentional (X40-X44)", "Drug poisonings (overdose) Suicide (X60-X64)", "Drug poisonings (overdose) Undetermined (Y10-Y14)","Drug poisonings (overdose) Homicide (X85)" ]
vital_stats_new=vital_stats[vital_stats["Drug/Alcohol Induced Cause"].isin(cod)]
vital_stats_new

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
1,"Baldwin County, AL",1003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
38,"Jefferson County, AL",1073.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0
54,"Mobile County, AL",1097.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0
78,"Anchorage Borough, AK",2020.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0
91,"Matanuska-Susitna Borough, AK",2170.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0
...,...,...,...,...,...,...
4744,"Waukesha County, WI",55133.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,34
4750,"Winnebago County, WI",55139.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,22
4760,"Fremont County, WY",56013.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10
4766,"Laramie County, WY",56021.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13
4770,"Natrona County, WY",56025.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13

In [34]:
vital_stats_new[vital_stats_new["Deaths"]=="Missing"]

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
118,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
119,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
120,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
121,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
127,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
128,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
129,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
130,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
139,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
140,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
141,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
142,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
4410,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
4411,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
4412,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
4413,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
4424,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
4425,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
4426,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
4427,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing

In [36]:
vital_stats_new["State_Code"] = vital_stats_new["County"].str[-2:].copy()
vital_stats_new

/var/folders/01/5cwkh1qx51s66l5bqmy3qfs80000gn/T/ipykernel_16085/2128726468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vital_stats_new["State_Code"] = vital_stats_new["County"].str[-2:].copy()

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State_Code
1,"Baldwin County, AL",1003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,AL
38,"Jefferson County, AL",1073.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0,AL
54,"Mobile County, AL",1097.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0,AL
78,"Anchorage Borough, AK",2020.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0,AK
91,"Matanuska-Susitna Borough, AK",2170.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,AK
...,...,...,...,...,...,...,...
4744,"Waukesha County, WI",55133.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,34,WI
4750,"Winnebago County, WI",55139.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,22,WI
4760,"Fremont County, WY",56013.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10,WY
4766,"Laramie County, WY",56021.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13,WY
4770,"Natrona County, WY",56025.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13,WY

In [37]:
#Subsetting for states we require for our analysis
states = ["FL","MD","DE","NY","TX","SC","NC","UT","PA","NV","NH"]
vs_states = vital_stats_new[vital_stats_new["State_Code"].isin(states)]
vs_states

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State_Code
488,"Kent County, DE",10001.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,DE
490,"New Castle County, DE",10003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,41.0,DE
491,"New Castle County, DE",10003.0,2003-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,13.0,DE
500,"Alachua County, FL",12001.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,FL
504,"Bay County, FL",12005.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,21.0,FL
...,...,...,...,...,...,...,...
4256,"Utah County, UT",49049.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,62,UT
4257,"Utah County, UT",49049.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,15,UT
4258,"Utah County, UT",49049.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,20,UT
4262,"Washington County, UT",49053.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,27,UT
4266,"Weber County, UT",49057.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,56,UT

In [38]:
vs_states.State_Code.value_counts()

FL    645
TX    537
PA    531
NC    456
NY    364
MD    229
SC    198
UT    126
NH     69
NV     67
DE     42
Name: State_Code, dtype: int64