In [1]:
import pandas as pd
import numpy as np

#importing the Data
death_03_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2003.txt", sep="\t")
death_04_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2004.txt", sep="\t")
death_05_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2005.txt", sep="\t")
death_06_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2006.txt", sep="\t")
death_07_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2007.txt", sep="\t")
death_08_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2008.txt", sep="\t")
death_09_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2009.txt", sep="\t")
death_10_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2010.txt", sep="\t")
death_11_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2011.txt", sep="\t")
death_12_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2012.txt", sep="\t")
death_13_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2013.txt", sep="\t")
death_14_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2014.txt", sep="\t")
death_15_df = pd.read_csv("/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/00_source_data/US_VitalStatistics/Underlying Cause of Death, 2015.txt", sep="\t")

In [2]:
# Looking at the head of the data
death_03_df.head()

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,NaN,"Autauga County, AL",1001.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,NaN,"Baldwin County, AL",1003.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,NaN,"Barbour County, AL",1005.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0

In [3]:
# Combining all the datasets
vital_stats = pd.concat([death_03_df,death_04_df,death_05_df,death_06_df,death_07_df,death_08_df,death_09_df,death_10_df,death_11_df,death_12_df,death_13_df,death_14_df,death_15_df])

In [4]:
# Checking if all datasets combined correctly
vital_stats.sample(40)

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
3331,NaN,"Rutherford County, TN",47149.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,1235.0
129,NaN,"Navajo County, AZ",4017.0,2005.0,2005.0,All other alcohol-induced causes,A9,30.0
1835,NaN,"Montcalm County, MI",26117.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,540.0
136,NaN,"Pinal County, AZ",4021.0,2005.0,2005.0,Drug poisonings (overdose) Unintentional (X40-...,D1,15.0
4273,NaN,"Lynchburg city, VA",51680.0,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,770.0
3706,NaN,"Archer County, TX",48009.0,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,71.0
4184,NaN,"Bayfield County, WI",55007.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,156.0
12,NaN,"Chilton County, AL",1021.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,438.0
2154,NaN,"Stevens County, MN",27149.0,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,76
571,NaN,"Clay County, FL",12019.0,2012.0,2012.0,All other alcohol-induced causes,A9,10.0
4498,NaN,"Raleigh County, WV",54081.0,2014.0,2014.0,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0
362,NaN,"San Joaquin County, CA",6077.0,2012.0,2012.0,All other alcohol-induced causes,A9,66.0
1770,NaN,"Wayne County, MI",26163.0,2003.0,2003.0,All other drug-induced causes,D9,160.0
1024,NaN,"Shoshone County, ID",16079.0,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,158
159,NaN,"Yavapai County, AZ",4025.0,2012.0,2012.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,14.0
2822,NaN,"Richmond County, NY",36085.0,2015.0,2015.0,Drug poisonings (overdose) Unintentional (X40-...,D1,74
1539,NaN,"Vernon Parish, LA",22115.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,388.0
637,NaN,"Orange County, FL",12095.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,6348.0
2270,NaN,"Missoula County, MT",30063.0,2008.0,2008.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13.0
4102,NaN,"Dane County, WI",55025.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,2584.0
3676,NaN,"Sabine County, TX",48403.0,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,152.0
1313,NaN,"Atchison County, KS",20005.0,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,179.0
3086,NaN,"Berks County, PA",42011.0,2006.0,2006.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
3145,NaN,"Washita County, OK",40149.0,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,134.0
1613,NaN,"Rowan County, KY",21205.0,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,220.0
422,NaN,"Boulder County, CO",8013.0,2008.0,2008.0,All other alcohol-induced causes,A9,35.0
2497,NaN,"Gosper County, NE",31073.0,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,25
3005,NaN,"Brown County, OH",39015.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,17.0
2490,NaN,"Hudson County, NJ",34017.0,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,32.0
586,NaN,"Hernando County, FL",12053.0,2007.0,2007.0,All other alcohol-induced causes,A9,22.0
2357,NaN,"Johnson County, NE",31097.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,65.0
2836,NaN,"Pender County, NC",37141.0,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,431.0
2164,NaN,"Dawson County, NE",31047.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,219.0
3553,NaN,"Unicoi County, TN",47171.0,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,222.0
2507,NaN,"Caswell County, NC",37033.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,243.0
2320,NaN,"St. Louis city, MO",29510.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,85.0
3210,NaN,"Washington County, RI",44009.0,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,1023.0
3598,NaN,"Sevier County, TN",47155.0,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,23.0
3132,NaN,"Florence County, SC",45041.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,1347.0
1319,NaN,"Black Hawk County, IA",19013.0,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,1105

In [5]:
# Dropping Notes and Year Code columns. Notes has too many null values and Year Code is a redundant column
vital_stats = vital_stats.drop(["Notes","Year Code"], axis = 1)
vital_stats.head()

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,"Baldwin County, AL",1003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,"Baldwin County, AL",1003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,"Baldwin County, AL",1003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,"Barbour County, AL",1005.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0

In [6]:
# Looking at the dimension of the dataset
vital_stats.shape

(57436, 6)

In [7]:
# Checking data types of each column and null values
vital_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57436 entries, 0 to 4797
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County                           57241 non-null  object
 1   County Code                      57241 non-null  float64
 2   Year                             57241 non-null  float64
 3   Drug/Alcohol Induced Cause       57241 non-null  object
 4   Drug/Alcohol Induced Cause Code  57241 non-null  object
 5   Deaths                           57241 non-null  object
dtypes: float64(2), object(4)
memory usage: 3.1+ MB

In [8]:
# Looking at total null values
vital_stats.isna().sum()

County                             195
County Code                        195
Year                               195
Drug/Alcohol Induced Cause         195
Drug/Alcohol Induced Cause Code    195
Deaths                             195
dtype: int64

In [9]:
#Dropping all na values
vital_stats.dropna(inplace=True)

In [10]:
# Verifying if all null values are removed
vital_stats.isna().sum()

County                             0
County Code                        0
Year                               0
Drug/Alcohol Induced Cause         0
Drug/Alcohol Induced Cause Code    0
Deaths                             0
dtype: int64

In [11]:
# Changing datatype for the Year column to date time
vital_stats["Year"] = pd.to_datetime(vital_stats["Year"],format="%Y")

In [12]:
# Verifying change in datetime
vital_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57241 entries, 0 to 4782
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County                           57241 non-null  object
 1   County Code                      57241 non-null  float64
 2   Year                             57241 non-null  datetime64[ns]
 3   Drug/Alcohol Induced Cause       57241 non-null  object
 4   Drug/Alcohol Induced Cause Code  57241 non-null  object
 5   Deaths                           57241 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 3.1+ MB

In [13]:
# Looking at the unique causes of death
vital_stats["Drug/Alcohol Induced Cause"].value_counts()

All other non-drug and non-alcohol causes             40337
Drug poisonings (overdose) Unintentional (X40-X44)     7573
All other alcohol-induced causes                       6123
Drug poisonings (overdose) Suicide (X60-X64)           1465
Drug poisonings (overdose) Undetermined (Y10-Y14)       761
All other drug-induced causes                           628
Alcohol poisonings (overdose) (X45, X65, Y15)           349
Drug poisonings (overdose) Homicide (X85)                 5
Name: Drug/Alcohol Induced Cause, dtype: int64

In [14]:
# Filtering the data drug related deaths
cod = [
    "Drug poisonings (overdose) Unintentional (X40-X44)",
    "Drug poisonings (overdose) Suicide (X60-X64)",
    "Drug poisonings (overdose) Undetermined (Y10-Y14)",
    "Drug poisonings (overdose) Homicide (X85)",
]
vital_stats_new = vital_stats[vital_stats["Drug/Alcohol Induced Cause"].isin(cod)]
vital_stats_new

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
1,"Baldwin County, AL",1003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
38,"Jefferson County, AL",1073.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0
54,"Mobile County, AL",1097.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0
78,"Anchorage Borough, AK",2020.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0
91,"Matanuska-Susitna Borough, AK",2170.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0
...,...,...,...,...,...,...
4744,"Waukesha County, WI",55133.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,34
4750,"Winnebago County, WI",55139.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,22
4760,"Fremont County, WY",56013.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10
4766,"Laramie County, WY",56021.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13
4770,"Natrona County, WY",56025.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13

In [15]:
#On trying to convert column "Death" to numeric, noted there is a string value called Missing
# Looking at the rows where data for death is not available
vital_stats_new[vital_stats_new["Deaths"]=="Missing"]

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
118,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
119,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
120,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
121,"Prince of Wales-Outer Ketchikan Census Area, AK",2201.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
127,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
128,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
129,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
130,"Skagway-Hoonah-Angoon Census Area, AK",2232.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
139,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
140,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
141,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
142,"Wrangell-Petersburg Census Area, AK",2280.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
4410,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
4411,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
4412,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
4413,"Bedford city, VA",51515.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing
4424,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,Missing
4425,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Suicide (X60-X64),D2,Missing
4426,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Homicide (X85),D3,Missing
4427,"Clifton Forge city, VA",51560.0,2015-01-01,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,Missing

In [16]:
# We will drop the data for Alaska, keep data for VA as is for now
# First we need to separate our state and county values into separate variables

In [17]:
#Creating State Codes
vital_stats_new["State_Code"] = vital_stats_new["County"].str[-2:].copy()

/var/folders/01/5cwkh1qx51s66l5bqmy3qfs80000gn/T/ipykernel_23459/3762576489.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vital_stats_new["State_Code"] = vital_stats_new["County"].str[-2:].copy()

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State_Code
1,"Baldwin County, AL",1003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,AL
38,"Jefferson County, AL",1073.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0,AL
54,"Mobile County, AL",1097.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0,AL
78,"Anchorage Borough, AK",2020.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0,AK
91,"Matanuska-Susitna Borough, AK",2170.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,AK
...,...,...,...,...,...,...,...
4744,"Waukesha County, WI",55133.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,34,WI
4750,"Winnebago County, WI",55139.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,22,WI
4760,"Fremont County, WY",56013.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10,WY
4766,"Laramie County, WY",56021.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13,WY
4770,"Natrona County, WY",56025.0,2015-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,13,WY

In [18]:
#Subsetting for states we require for our analysis
# states = ["FL","MD","DE","NY","TX","SC","NC","UT","PA","NV","NH"]
# vs_states = vital_stats_new[vital_stats_new["State_Code"].isin(states)]
# vs_states

In [20]:
new = vital_stats_new["County"].str.split(",", n = 1, expand = True)
vital_stats_new["County_Name"] = new[0]

/var/folders/01/5cwkh1qx51s66l5bqmy3qfs80000gn/T/ipykernel_23459/2103717168.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vital_stats_new["County_Name"] = new[0]

In [21]:
# Looking at the dataset with the two new columns
vital_stats_new.head()

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State_Code,County_Name
1,"Baldwin County, AL",1003.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,AL,Baldwin County
38,"Jefferson County, AL",1073.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0,AL,Jefferson County
54,"Mobile County, AL",1097.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0,AL,Mobile County
78,"Anchorage Borough, AK",2020.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0,AK,Anchorage Borough
91,"Matanuska-Susitna Borough, AK",2170.0,2003-01-01,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,AK,Matanuska-Susitna Borough

In [22]:
# Dropping Alaska from our data set
vital_stats_final = vital_stats_new[vital_stats_new["State_Code"]!="AK"]

In [24]:
# Checking if AK statecode is still present in the data
vital_stats_final[vital_stats_final["State_Code"] == "AK"]

Empty DataFrame
Columns: [County, County Code, Year, Drug/Alcohol Induced Cause, Drug/Alcohol Induced Cause Code, Deaths, State_Code, County_Name]
Index: []

In [26]:
vital_stats_final.to_csv('/Users/Aarushi/Duke/MIDS - Fall 2021/Fall 2021/720_IDS_PDS/pds2021-opioids-team-2-ids720/20_intermediate_files/vital_stata.csv', encoding='utf-8')